### ISSUE TITLE
incorrect repository name

### ISSUE THREAD

**Issue by danmarsden** [DevEticeo/moodle-block_shelf_badge#1]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin. - your repository name of "moodle-block_shelf_badges" makes it look like your plugin should be installed in the "shelf_badges" folder, however... it's actually called "shelf_badge" instead. :-) - would be good to remove that extra "s" at the end... first time I installed your plugin it failed because I'd used "badges" - and I won't be the only one to make that mistake! :-)

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by DevEticeo** [comment]
Hi Dan,
Many thanks for your feedbacks.

We fixed the repository name.

Thanks again for the help !
