### ISSUE TITLE
Please check supported versions

### ISSUE THREAD

**Issue by danmarsden** [DevEticeo/moodle-block_shelf_badge#10]
in your version.php file you specify a requires version that matches Moodle 3.4 so your moodle.org plugins entry states that your plugin supports moodle 3.4 -> 4.0 - can you please check this? - have you tested it in Moodle 3.4? - if not you might want to set it to a requires version that matches something like Moodle 3.9

thanks!

**Comment by DevEticeo** [comment]
Hi Dan,
Many thanks for your feedbacks.

Agreed, we test plugin in 3.9 so we update requires version.
