### ISSUE TITLE
hard coded english lang strings

### ISSUE THREAD

**Issue by danmarsden** [DevEticeo/moodle-block_shelf_badge#3]
https://github.com/DevEticeo/moodle-block_shelf_badges/blob/main/block_shelf_badge.php#L97

https://github.com/DevEticeo/moodle-block_shelf_badges/blob/main/js/edit-form.js#L27

note this is a blocker for plugins db approval.

**Comment by DevEticeo** [comment]
Hi Dan,
Many thanks for your feedbacks.

We corrected this hard coded lang strings.
