### ISSUE TITLE
undocumented use of CDNs for js includes

### ISSUE THREAD

**Issue by danmarsden** [DevEticeo/moodle-block_shelf_badge#4]
https://github.com/DevEticeo/moodle-block_shelf_badges/blob/main/edit_form.php#L83-L85

Please add information to your readme to state you use external sources for JS - many sites will implement their own CSP policies and could block these from loading.

It would also be good to check if you can instead rely on the jquery libraries that ship with existing Moodle core code rather than using external sources for this.

**Comment by DevEticeo** [comment]
Hi Dan,
Many thanks for your feedbacks.

We added information in our readme. 
Next time, we will try to don't use external sources for JS
