### ISSUE TITLE
please use placeholders in db queries to prevent sql injection.

### ISSUE THREAD

**Issue by danmarsden** [DevEticeo/moodle-block_shelf_badge#5]
https://github.com/DevEticeo/moodle-block_shelf_badges/blob/main/block_shelf_badge.php#L130

userroles and userid values should be using placeholders and passed as parameters.

more information on this see:
https://moodledev.io/general/development/policies/security/sql-injection

your userrole part will probably need to use a helper function like get_in_or_equal as per:
https://moodledev.io/docs/apis/core/dml#get_in_or_equal

**Comment by DevEticeo** [comment]
Hi Dan,
Many thanks for your feedbacks.

We fixed this problems thanks to your documentations links

Thanks again for the help !
