### ISSUE TITLE
simple_block() appears to iterate over all site categories and all courses asking for badges from each

### ISSUE THREAD

**Issue by danmarsden** [DevEticeo/moodle-block_shelf_badge#7]
This is really in-efficient - think about a course with 10,000 courses - and a user is only enrolled in 3 or 4 of them - it's really in-efficient to iterate over every course asking if it has badges for this user - this could end up making your block load really slowly and potentially even cause the page load to timeout.

It would be much better to just call something like:
badges_get_user_badges($USER->id);

and getting all the badges for this user in one go.

I'm not a big user of the badges api - but I note that it also has a concept of "public vs non-public" badges - it would be good to check that you are correctly displaying these types of badges. - should your plugin display non-public badges?

**Comment by DevEticeo** [comment]
Hi Dan,
Many thanks for your feedbacks.

Totally agreed, we fixed the in-efficient interator.

We are not familiar with the public / non-public concept too... But we add this in our todo list, maybe in futher version ! 
Our platformes use only public badge but we need to deal with non-public badges...
